### ISSUE TITLE
Move `master` branch to `main`

### ISSUE THREAD

**Issue by jennybc** [r-lib/evaluate#102]
The `master` branch of this repository will soon be renamed to `main`, as part of a coordinated change across several GitHub organizations (including, but not limited to: [tidyverse](https://github.com/tidyverse), [r-lib](https://github.com/r-lib), [tidymodels](https://github.com/tidymodels), and [sol-eng](https://github.com/sol-eng)). We anticipate this will happen by the end of September 2021.

That will be preceded by a release of the [usethis package](https://usethis.r-lib.org), which will gain some functionality around detecting and adapting to a renamed default branch. There will also be a blog post at the time of this `master` --> `main` change.

The purpose of this issue is to:

* Help us firm up the list of targetted repositories
* Make sure all maintainers are aware of what's coming
* Give us an issue to close when the job is done
* Give us a place to put advice for collaborators re: how to adapt

*message id: euphoric_snowdog*

**Comment by yihui** [comment]
Done. Thanks!

**Comment by jennybc** [comment]
FYI I plan to do this all at once, timed to occur with a blog post and a usethis release. We won't undo this change here, but just know that I'm opening these issues in advance of the change on purpose. I can make the branch change just as easily as I'm opening these issues (it's all automated), but I'm hoping to do the bulk of this in a coordinated way, to better support what needs to happen in thousands of local repos and forks.

**Comment by yihui** [comment]
Sorry, I thought it was like one of the several issues that @apreshill filed in the past (e.g. https://github.com/rstudio/rmarkdown/issues/2181). Since it only takes seconds for me to do by hand, I just did all of them by hand.

Just to be clear, did I make a mistake?

> to better support what needs to happen in thousands of local repos and forks.

I'm just curious here---you can bulk rename the branches in the remote repositories, but you can't rename them in local repos or forks, and everyone has to rename their branches locally by themselves, right? What does "better support" mean here?

**Comment by jennybc** [comment]
Re: what I mean by "better support":

> That will be preceded by a release of the usethis package, which will gain some functionality around detecting and adapting to a renamed default branch. There will also be a blog post at the time of this `master` --> `main` change.

So, in general, I plan to make this change all at once (I'm dealing with several hundred repos) and have one blog post announcing the change and laying out user's best options for updating their own stuff.

**Comment by yihui** [comment]
I see. It sounds like usethis will provide a wrapper of some git commands.

I hope I didn't stand in your way. If I did, I'd be happy to rename it back to `master` and wait for your bulk renaming.

**Comment by jennybc** [comment]
> It sounds like usethis will provide a wrapper of some git commands.

Yeah, usethis already provides a fair amount of support for specific Git / GitHub workflows (all via the gert or gh packages), so all aspects of the `master` --> `main` change will be accounted for (for an admin/maintainer or for a collaborator).

No, there's no reason to switch this one back. I'll switch a few repos early anyway (repos with very few forks / external collaborators), to work out all the kinks in my tools and recommendations for the blog post. I think evaluate is probably one of the repos where development is concentrated in just a few hands, so it won't lead to much confusion / questions.
