### ISSUE TITLE
is.atomic(x): please assume `is.atomic(NULL)` may/will give `FALSE`

### ISSUE THREAD

**Issue by mmaechler** [r-lib/evaluate#106]
https://github.com/r-lib/evaluate/blob/020225350e12db45ed2f14aa4fe2ed9e0042407e/R/eval.r#L104  

The `R-is` branch is a version of uptodate R-devel  but with  `is.atomic(NULL)`  giving `FALSE` instead of `TRUE`
If the above line 104 in `evaluate_call()`  gets an    ` || is.null `  added, this will not change anything in current R, but will allow
*testthat* (yes!) to work correctly in some cases, e.g., when R CMD checking `pillar`.

I'd appreciate a lot if you could do this *and* release to CRAN  ((because we have been checking all of CRAN + some BioC with the R-is branch and have seen errors because of this line in package `evaluate`)).

**Comment by yihui** [comment]
Thank you very much for the report! I just committed the fix, and will do a CRAN release tomorrow.

**Comment by yihui** [comment]
The new version is on CRAN now.

**Comment by mmaechler** [comment]
Thanks a lot, Yihui !!
