### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by chiehchangchen** [r-lib/evaluate#108]
I tried to install the package, but it failed. The error messages are as followed

Warning in parse(con, encoding = "UTF-8") :
  argument encoding="UTF-8" is ignored in MBCS locales
Error in parse(con, encoding = "UTF-8") : 
  invalid multibyte character in parser at line 11
ERROR: installing package DESCRIPTION failed for package 'evaluate'

I guess it is because the special character ("Karolis", "Koncevičius") in the DESCPRIPTION file
I've tried "Sys.setlocale("LC_ALL","English")", but the installation still failed
Would you please help?

**Comment by yihui** [comment]
You may try to install the binary version:

```r
install.packages('evaluate', type = 'binary')
```

**Comment by chiehchangchen** [comment]
Yihui, thank you!
