### ISSUE TITLE
Automatic flush after encountering newline

### ISSUE THREAD

**Issue by fkohrt** [r-lib/evaluate#115]
When running R code from Jupyter notebooks using [IRkernel](https://github.com/IRkernel/IRkernel), `print()`ed output only appears after one cell has finished.

Take the following example, executed in a Jupyter notebook:

```r
f <- function() {
    for (i in 1:3) {
        print(i)
        # flush.console()
        Sys.sleep(1)
    }
}
```

Executing `f()` in another cell will only show continuous output if `flush.console()` becomes uncommented. Real-life use cases include running `install.packages(...)` and not getting any update as well as using streaming functions that are supposed to provide continous output (see IRkernel/IRkernel#625).

Therefore it would be great if {evaluate} could autoflush after encountering a newline (`\n`, `\r`).

**Comment by yihui** [comment]
I'm afraid this is not possible in **evaluate**. The `for` loop is a single expression, and **evaluate** can't capture its output until the whole expression has been evaluated: https://github.com/r-lib/evaluate/blob/33f2c80c77f11dc586f7c134a3fa568735d3f1b0/R/eval.r#L200-L208

In other words, **evaluate** doesn't support displaying streaming data.

**Comment by fkohrt** [comment]
I see, that's really unfortunate.
