### ISSUE TITLE
generate plots in loop with knitr - possible bug in evaluate

### ISSUE THREAD

**Issue by szilard** [r-lib/evaluate#14]
I'm trying to generate text-plot pairs with knitr (-> markdown -> html). I have reported a bug on the knitr list and I was referred here, see below:

``````
```{r echo=FALSE}
for(i in 1:3) {
    cat(i)
    plot(i)
}
``````

I'd like to get this:

1
plot1
2
plot2
...

Instead, I get this:

1
2
plot1
3
plot2
plot3

Yihui referred me to:

```
evaluate("
for(i in 1:3) {
    cat(i)
    plot(i)
}")
```

which gives:
...
[[3]]
[1] "1"

[[4]]
[1] "2"

[[5]]

[[6]]
[1] "3"

[[7]]

[[8]]

instead of 

[[3]]
[1] "1"

[[4]]

[[5]]
[1] "2"

[[6]]

[[7]]
[1] "3"

[[8]]

Originally reported on the knitr list:
https://groups.google.com/group/knitr/browse_thread/thread/ddc3bb29c4c953e8

**Comment by Freedomtowin** [comment]
If you use plot.new() after each plot, it will allow duplicates to show up correctly.

**Comment by samyishak** [comment]
This is years old now, but I'm wondering if there's any hope on this issue. I'm trying to interleave text and plot outputs via loop to an R Notebook preview in RStudio.

Case 1: works for the output I want [text, plot, text, plot], but requires putting the plot before the text:
```
```{r, results='asis'}
for(i in 1:2) {
  plot(i)
  cat(i)
}
```
Case 2: how I would expect to get Case 1, but instead outputs [text, text, plot, plot]:
```
```{r, results='asis'}
for(i in 1:2) {
  cat(i)
  plot(i)
}
```

This pattern seems to hold if you want more than one plot, but you only need the *first* plot to precede the text to get the intended output of [text, many plots, text, many plots]:
```
```{r, results='asis'}
for(i in 1:2) {
  plot(i)
  cat(i)
  plot(i*2)
  plot(i*3)
}
```

```
Session info -------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.408)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Phoenix             
 date     2018-02-02                  

Packages -----------------------------------------------------------------------------------------
 package       * version date       source        
 base          * 3.4.3   2018-01-10 local         
 compiler        3.4.3   2018-01-10 local         
 curl            3.1     2017-12-28 local         
 datasets      * 3.4.3   2018-01-10 local         
 devtools        1.13.4  2017-11-09 CRAN (R 3.4.3)
 digest          0.6.13  2017-12-14 CRAN (R 3.4.3)
 graphics      * 3.4.3   2018-01-10 local         
 grDevices     * 3.4.3   2018-01-10 local         
 jsonlite        1.5     2017-06-01 CRAN (R 3.3.2)
 memoise         1.1.0   2017-04-21 CRAN (R 3.4.3)
 methods       * 3.4.3   2018-01-10 local         
 RevoUtils     * 10.0.7  2018-01-02 local         
 RevoUtilsMath * 10.0.1  2017-09-19 local         
 RPushbullet   * 0.3.1   2017-02-17 CRAN (R 3.4.3)
 stats         * 3.4.3   2018-01-10 local         
 tools           3.4.3   2018-01-10 local         
 utils         * 3.4.3   2018-01-10 local         
 withr           2.1.1   2017-12-19 CRAN (R 3.4.3)
 yaml            2.1.16  2017-12-12 CRAN (R 3.4.3)
```
Also want to say everything coming from RStudio and the tidyverse is just fantastic, so thank you.

**Comment by samyishak** [comment]
Oh jeez, I missed the last comment by Freedomtowin. This makes the order of the output match the order of the calls, but adds large plot-size spaces in the R Notebook output, is there any way around the spacing?:
```
```{r, results='asis'}
for(i in 1:2) {
  cat(i)
  plot(i)
  plot.new()
  plot(i*2)
  plot.new()
  plot(i*3)
  plot.new()
}
```
