### ISSUE TITLE
CRAN release has minimum dependency on R4.0.0

### ISSUE THREAD

**Issue by PietrH** [r-lib/evaluate#205]
I'm trying to install roxygen2 on a R3.6.3 machine, but I'm failing because knitr is dependent on evaluate which, on CRAN, has a minimum R dependency of R (≥ 4.0.0). 

I see the dev version on here has a minium dep on R3.6.0

Is there any particular reason for this?

**Comment by hadley** [comment]
See extensive discussion in #173
