### ISSUE TITLE
Rmd file does not respect options()$warn across chunks

### ISSUE THREAD

**Issue by ppoyk** [r-lib/evaluate#213]
Hello,

There seems to be an issue in how the `warning` option is handled inside an Rmd file.
This relates to an earlier pull request https://github.com/r-lib/evaluate/pull/81#issue-251835531 and the original issue on https://github.com/yihui/knitr/issues/1425#issue-251433392

The `warn` option does not correctly persist across the Rmd file chunks.

Here is an example code to test the behaviour:

    ```{r pt1}
    f <- function(x) {warning("Warning raised!"); x}

    options(warn = 0)
    options()$warn
    f(TRUE)
    ```

    ```{r pt2}
    options(warn = 1)
    options()$warn
    f(TRUE)

    options(warn = 2)
    ```

    ```{r ops-fail}
    options()$warn
    f(TRUE)
    ```

Last `options()$warn` reports value of `1`, and thus the last call to `f()` does not raise an error, even though the option was explicitly set in the previous code chunk.

I hope this is helpful.

**Comment by hadley** [comment]
This is out of scope for evaluate since it only handles evaluation of a single chunk. I think knitr is the right place to file the bug.

**Comment by ppoyk** [comment]
Thank you for your swift answer. I have created an issue for `knitr`: https://github.com/yihui/knitr/issues/2357#issue-2417959350
