### ISSUE TITLE
evaluate appears not to catch all output?

### ISSUE THREAD

**Issue by MichelNivard** [r-lib/evaluate#229]
when I run:

```
evaluate::evaluate("?hist()")
```

or

```
evaluate::evaluate("help(hist)")
```

the contents of the help page aren't caught and cant be replayed? is this a bug or expected behaviour?

**Comment by hadley** [comment]
Technically help files are not printed; they're opened in a separate viewer process. If you want to control this you could override `utils:::print.help_files_with_topic` with your own implementation.
