### ISSUE TITLE
Use correct encoding

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/evaluate#66]
on windows, to correctly parse text, you need to do:

``` r
parse(text = code, encoding = Encoding(code))
```

if the `code` has set an encoding, it gets returned by `Encoding`. Else, `Encoding` returns `'unknown'`, the default value for `encoding` in `parse`.

ideally, `parse_all` should internally do the above instead of a `encoding`-less `parse` call.

an alternative would be to pass down an `encoding` parameter through `evaluate` → `parse_all` → `parse`

**Comment by janschulz** [comment]
This isn't the problem here: it seems that encodeing make sno difference at all:

```R
> s <- '"法 \\u8FDB"'
> parse(text=s, encoding = Encoding(s))
expression("<U+6CD5> \u8FDB")
> s <- '"法 \\u8FDB"'
> Encoding(s)
[1] "UTF-8"
> parse(text=s, encoding = Encoding(s))
expression("<U+6CD5> \u8FDB")
```

Just to show the original problem:

```R
library(evaluate)

code <- "
x = '法'
y = '\\u8FDB'
print(nchar(x))
print(nchar(y))
print(x)
print(y)
"


l = list()
txt <- function(o, type) {
  t <- paste(o, collapse = '\n')
  l[length(l)+1] <<- t
}
oh <- new_output_handler(source = identity, 
                         text = function(o) txt(o, "text"), 
                         graphics = identity,
                         message = identity, 
                         warning = identity, 
                         error = identity, 
                         value = identity)


x <- evaluate(code, output_handler = oh)
l
```

```
> l
[[1]]
[1] "[1] 8\n" # -> the unicode char is already wring when it gets executed

[[2]]
[1] "[1] 1\n"

[[3]]
[1] "[1] \"<U+6CD5>\"\n"

[[4]]
[1] "[1] \"<U+8FDB>\"\n" # -> And even "good" unicode chars get mangled on the way out.
```

**Comment by flying-sheep** [comment]
OK. code is obviously good UTF-8 since it comes from user input, right?

doesn’t that mean that using `parse(text = code, encoding = Encoding(code))` creates the right object, and only the printing gets messed up?

if so, will our `capture.output(print(obj))` introduce the error?

**Comment by flying-sheep** [comment]
important printing stuff (i think)

[WinUTF8out](https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/main/connections.c#L4851-L4855) and [EncodeString](https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/main/printutils.c#L549-L565)

**Comment by janschulz** [comment]
> doesn’t that mean that using parse(text = code, encoding = Encoding(code)) creates the right object, and only the printing gets messed up?

No: it's already messed up because `nchar(x)` in the evaluate call returns 8, which happens when it sees a string like `<U+6CD5>`.

**Comment by janschulz** [comment]
Knitr has the same problem:

```r
# code cell marker broken to not confuse github...
` ``{r} 
x = '法'
y = '\u8FDB'
print(nchar(x))
print(nchar(y))
print(x)
print(y)
x
y
` ``
```

Outputs:

```
## [1] 8
## [1] 1
## [1] "<U+6CD5>"
## [1] "<U+8FDB>"
## [1] "<U+6CD5>"
## [1] "<U+8FDB>"
```

**Comment by janschulz** [comment]
And this also doesn't make a difference (in RStudio, win7):

```
> f <- textConnection("rval2", "w", local=TRUE, encoding = "UTF-8")
> sink(f)
> print('法')
> print('\u8FDB')
> sink()
> print(rval2)
[1] "[1] \"<U+6CD5>\"" "[1] \"<U+8FDB>\""
```

**Comment by expectopatronum** [comment]
I once had a problem with encoding when the locale of my RStudio was not set. You find out by `Sys.getlocale()`
I'm not sure if this applies here though.

**Comment by janschulz** [comment]
```
> Sys.getlocale()
[1] "LC_COLLATE=German_Germany.1252;LC_CTYPE=German_Germany.1252;LC_MONETARY=German_Germany.1252;LC_NUMERIC=C;LC_TIME=German_Germany.1252"
```
-> Looks ok to me (this is a plain RStudio session on win7)

The problem is that the executed code is UTF-8 (e.g. read from a file) and the output should also be UTF-8 (eg written to a file), so the locale should not matter?

**Comment by yihui** [comment]
I think there is something fundamentally broken (related to `sink()`) in base R on Windows. See #59. Basically if the characters are not supported by the system native encoding, they will be silently converted to `<U+XXXX>` sequences.

**Comment by janschulz** [comment]
Any idea how to get out of this problem? This is basically a big problem in the current R kernel, because the "in" side of this problem prevents unicode code input on windows, resulting in wrong computations (e.g. probably wrong comparisons if one side comes from a file and one from a string defined in the notebook).

**Comment by yihui** [comment]
No, I think this requires one to dig deep into the C code in base R, and I don't really understand that level of details.

This is a problem, but probably not as big as you imagined. This only becomes a problem when a Windows user has characters in the document that his/her Windows native character encoding does not support. I think this is relatively rare. In the above examples, as long as your Windows supports the Chinese locale, you should be fine (`Sys.setlocale(, 'Chinese')`). As you mentioned, knitr suffers from the same problem, but over the four years, this issue has bitten users at most three times as far as I can remember.

**Comment by speechchemistry** [comment]
Thank you for all your work on this. This comment is coming from someone still trying to understand the issue but I believe this is a problem for those of us who work with under-resourced languages, and linguists working with IPA data. If I've understood correctly, this issue is a problem for about half of the world's languages. 

> This is a problem, but probably not as big as you imagined.

**Comment by yihui** [comment]
@speechchemistry We had to wait for Windows to support UTF-8; see #59. R core has been making effort: https://developer.r-project.org/Blog/public/2020/05/02/utf-8-support-on-windows/ Eventually we should be able to forget about character encodings on Windows. Trust me: my native language is Chinese, and [I have felt the enormous pain for many years](https://yihui.org/en/2018/11/biggest-regret-knitr/), but still have to wait.
