### ISSUE TITLE
error handler fails silently in some cases

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/evaluate#70]
the following code prints a empty `list()` although the list should contain the recursion error:

``` r
err <- list()
eh <- function(e) err <<- c(err, list(toString(e)))
oh <- evaluate::new_output_handler(error = eh)
evaluate::evaluate(
    'f<-function(x) f(x); f(0)',
    output_handler = oh,
    envir = .GlobalEnv,
    stop_on_error = 1L)
print(err)
```

if we however do `eh <- function(e) err <<- c(err, list(e))`, it’ll work. why?

**Comment by flying-sheep** [comment]
since @yihui said he has no idea, i thought about it some more…

maybe `toString` does something depending on the global stack trace info and somehow fails in the error function? maybe it can be debugged by writing stuff to a file (since the stdout/err capturing of evaluate interferes otherwise)

**Comment by flying-sheep** [comment]
hmm…

```r
eh <- function(e) {
	p <- pipe('cat', 'w')
	write('this works', p)
	tryCatch(
		toString(e),
		error = function(err) write('this doesn’t', p),
		finally = write('this neither', p))
	write('this isn’t reached', p)
	close(p)
	err <<- c(err, list(toString(e)))
}
```

**Comment by hadley** [comment]
When I run this now, I get:

```
Error : C stack usage  7954168 is too close to the limit
```

Likely related to #103
