### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jeroen** [r-lib/evaluate#79]
**Update** my initial diagnosis was wrong. It looks like somewhere there is some warm-up required: 

```r
> library(evaluate)
> options(device = function(file, ...){
+   pdf(NULL, ...)
+ })
>
> cl <- call("rnorm", 10)
>
> system.time(evaluate(cl))
   user  system elapsed
  0.107   0.005   0.113
> system.time(evaluate(cl))
   user  system elapsed
  0.118   0.003   0.123
> system.time(evaluate(cl))
   user  system elapsed
  0.002   0.000   0.002
> system.time(evaluate(cl))
   user  system elapsed
  0.003   0.000   0.005
```

This happens very consistently. The first two calls to `evaluate()` have about 100ms extra overhead.

**Comment by hadley** [comment]
I only see a slow down of ~20ms the first time evaluate is called in a session. I suspect it's because some package is getting loaded, or there's some other startup cost.
