### ISSUE TITLE
try() output not shown

### ISSUE THREAD

**Issue by krlmlr** [r-lib/evaluate#88]
``` r
evaluate::evaluate(quote(try(stop())))
#> [[1]]
#> $src
#> [1] "try(stop())"
#> 
#> attr(,"class")
#> [1] "source"
```

<sup>Created on 2018-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Is this by design? I would have expected the message shown by `try()` to be present in the output.

**Comment by krlmlr** [comment]
The problem here is that `try()` returns invisibly and prints its output to a stream indicated by the `outFile` argument, defaulting to `getOption("try.outFile")` (available as of R 3.4.0). This can be worked around:

``` r
# Capturing the message printed by try(), works as of R 3.4.0
try_result <- ""
con <- textConnection("try_result", open = "w")
options(try.outFile = con)
evaluate::evaluate(quote(try(stop())))
#> [[1]]
#> $src
#> [1] "try(stop())"
#> 
#> attr(,"class")
#> [1] "source"
textConnectionValue(con)
#> [1] "Error in try(stop()) : "
close(con)
```

<sup>Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

@hadley: Would you review a patch that makes use of this option?

**Comment by hadley** [comment]
It's more up to @yihui — I don't mind reviewing the PR, but Yihui will have to do the eventual package release.

**Comment by yihui** [comment]
I'll be happy to do the release. Thanks @krlmlr!
