### ISSUE TITLE
Destroy connections opened in tests

### ISSUE THREAD

**Issue by krlmlr** [r-lib/evaluate#92]
by numerous `file()` calls.

We could wrap with `withr::local_connection()`, perhaps implement a helper that creates a self-destructing connection.?

**Comment by yihui** [comment]
A helper function like this should be fine:

```r
evaluate_file = function(f, ...) {
  con = file(f); on.exit(close(con))
  evaluate(con, ...)
}
```

Then replace `evaluate()` with `evaluate_file()` in all tests that used `file()` without closing the connection.

**Comment by krlmlr** [comment]
This is not an error, `evaluate()` will open and close the connection (which is initially closed) via `parse_all()` .

Happy to submit a documentation update after #93.
