### ISSUE TITLE
Backslashed escaped in evaluate()

### ISSUE THREAD

**Issue by bslashevaluate** [r-lib/evaluate#95]
Hi
I don't usually do this and I apologise if I'm very wrong here.

We use evaluate() to verify SQL and SQL-ish transactions with a DB server. When a statement contains a backslash, there's no amount of escaping possible to get it to evaluate. 

 print('\\s')
[1] "\\s"

 evaluate("print('\\s')")
[[1]]
$src
[1] "print('\\s')"

attr(,"class")
[1] "source"

[[2]]
<simpleError: '\s' is an unrecognized escape in character string starting "'\s">

Problematic use case: 
 DBI::dbSendQuery(conn = conx, 
                          statement = "select split('ab c', '\\s')[0]")
[1] "ab"

Thanks

**Comment by bslashevaluate** [comment]
github formatting/markdown is actually breaking what I'm trying to show.

In every single instance of "\" in the above, I actually typed the symbol twice.

When displaying the post above, GH has turned my double-backslashes to single-backslashes.

**Comment by yihui** [comment]
This is [a very common confusion](https://xkcd.com/1638/) in programming. I don't have time to explain it to you, but you need four backslashes in this case (four means two, then two means one).
